version: 2
jobs:
  build:
    docker:
      - image: fpco/stack-build:lts-11.9
    working_directory: /home/stackage
    steps:
      - checkout
      - restore_cache:
          key: cache
      - run: stack build --test --only-dependencies --no-terminal --system-ghc
      - save_cache:
          key: cache
          paths:
            - ~/.stack
      - run: stack install --test --no-terminal --system-ghc
